### ISSUE TITLE
Guided research ends after providing Pokestop name

### ISSUE THREAD

**Issue by tehstone** [klords/Kyogre#23]
Repro:

- `!res`
- bot prompts for pokestop name
- provide exact name or partial name
- if the bot can't determine stop from partial name it will prompt the user to choose an option
- bot cleans up its responses but does not prompt user for quest task

**Comment by tehstone** [comment]
this seems to be resolved. Tested with a Pokestop name the bot matched, and one that required disambiguation.

**Comment by klords** [comment]
reopening until fix is merged in github
