### ISSUE TITLE
Moderation System - Phase 1

### ISSUE THREAD

**Issue by tehstone** [klords/Kyogre#31]
First phase of this system should be kept simple, the bare minimum need to guard against abuse at release.

Implement a 'bot ban' command for mods/admins to use at their discretion. Also an unban command. Perhaps `!kban <user> [optional reason]` and `!kunban <user>`.
Maintain a list of banned users.
Add to the checks such that any command will check that a user is not banned.
If a banned user runs a bot command, delete their message and DM them explaining that prior behavior has barred them from using the bot for the time being.

More complex and partially/fully automated moderation has been discussed in the past and can be implemented at a later time.

**Comment by klords** [comment]
implemented in #34
