### ISSUE TITLE
locations have 4 listings each

### ISSUE THREAD

**Issue by tehstone** [klords/Kyogre#41]
This can be seen either by reporting a raid using an ambiguous name, reporting a research task at a particular stop, or by using the `!gym` command.
![4xlisting](https://user-images.githubusercontent.com/1518350/45958274-e1102c80-bfcb-11e8-9a2c-e3197dfee8e1.PNG)

Each gym currently has 4 listings.

**Comment by klords** [comment]
It appears I botched integrating the updated gym data when covington was added, which impacted all locations. fixed now.
