### ISSUE TITLE
Hatch message sends multiple times

### ISSUE THREAD

**Issue by tehstone** [klords/Kyogre#45]
I reported a raid with hatch time of 3:34pm
myself and 1 other did the `!i` command
I then did a `!timerset 0` at 3:33pm

The bot continually sent the message that the egg had hatched and tagged both of us roughly every 30 seconds.

I tried `!archive` and the bot deleted that message and seemed to ignore it.

![crazy](https://user-images.githubusercontent.com/1518350/46047272-4b62c300-c0d9-11e8-9608-b01c9fcf93d1.PNG)

**Comment by tehstone** [comment]
The timerset and people showing interest does not seem to matter.

I just reported eggs with 1, 2, 3, 5 minutes until hatch and all channels do this once the egg hatches.
The hatch message is sent once per minute, the listings channel is not updated to move the raid from Eggs to Active Raids. 
The channel is renamed from 'level-5-egg' to 'mewtwo'.

**Comment by klords** [comment]
Thanks, that's good info. Sounds like the hatch method (eggtoraid I think) is failing out midway due to an error and then trying again, since the bot just thinks it's still unhatched. Will fix it tonight.
