### ISSUE TITLE
Here/Coming/Interested/Cancel for Raids

### ISSUE THREAD

**Issue by klords** [klords/Kyogre#7]
format instructions for adding other teams unclear, needs example

**Comment by tehstone** [comment]
Behavior seems mostly correct, but there is no way to update your current count from `interested` to `coming` or from `coming` to `here`. User must list at least their total party count again when doing follow up commands.

Low priority overall, probably good enough for initial rollout.

**Comment by tehstone** [comment]
Changing from I -> c -> h should be allowed without providing a count

**Comment by klords** [comment]
Yeah I encountered this last night. It also changed my party composition too (I used 2m 1v and giving the same total for subsequent commands changed all to valor). Definitely needs a fix before rollout (easy enough).
